#!/bin/bash

: <<=cut
=pod

=head1 NAME

pidcmd - Show the command run by a pid


=head1 SYNOPSIS

B<pidcmd> I<pids>


=head1 DESCRIPTION

B<pidcmd> show the command run by a pid. It is a bit similar to:

  ps aux | grep pid

but it avoid false positives (if I<pid> matches a part of another
line).


=head1 EXAMPLE

Show the command for pid 1

  pidcmd 1

Show the command for pid 1000 and 1002

  pidcmd 1000 1002
  

=head1 AUTHOR

Copyright (C) 2019-2020 Ole Tange,
http://ole.tange.dk and Free Software Foundation, Inc.


=head1 LICENSE

Copyright (C) 2012 Free Software Foundation, Inc.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
at your option any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.


=head1 DEPENDENCIES

B<pidcmd> uses B</proc/*/cmdline>.


=head1 SEE ALSO

B<ps>


=cut

for pid in "$@"; do 
    cat /proc/$pid/cmdline | xargs -0
done

