#!/bin/bash

"$@" 2>&1

: <<=cut
=encoding utf8

=head1 NAME

stdout - redirect standard error (stderr) to standard output (stdout)


=head1 SYNOPSIS

B<stdout> I<command>


=head1 DESCRIPTION

B<stdout> is a way to redirect all output to standard output (stdout).

Normally you can use '2>&1' to do the same, but if the command needs
to be quoted, it may be hard to get the quoting right. B<stdout> makes
that unnecessary.


=head1 AUTHOR

Copyright (C) 2017 Ole Tange,
http://ole.tange.dk and Free Software Foundation, Inc.


=head1 LICENSE

Copyright (C) 2012 Free Software Foundation, Inc.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
at your option any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.


=head1 SEE ALSO

B<bash>(1)


=cut
