#!/bin/bash

: <<=cut
=pod

=head1 NAME

mirrorpdf - Mirror PDF horizontally


=head1 SYNOPSIS

B<mirrorpdf> I<file.pdf>


=head1 DESCRIPTION

B<mirrorpdf> mirrors the pages of a PDF-file. Output is in
I<file>_mirror.pdf.

=head1 EXAMPLE

Mirror pages of foo.pdf:

  mirrorpdf foo.pdf

=head1 AUTHOR

Copyright (C) 2018 Ole Tange,
http://ole.tange.dk and Free Software Foundation, Inc.


=head1 LICENSE

Copyright (C) 2012 Free Software Foundation, Inc.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
at your option any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.


=head1 DEPENDENCIES

B<mirrorpdf> uses B<pdf2ps>, B<pstops>, B<pdftk>, and B<ps2pdf>.


=head1 SEE ALSO

B<man>


=cut

mirror() {
    tmp=`mktemp /tmp/mirpdfXXXXX`
    pdf2ps "$1" - |
	# Flip both horizontally and vertically
	pstops H |
	ps2pdf - $tmp
    # Flip both horizontally and vertically
    pdftk $tmp cat 1-endnorth output "$2"
    rm $tmp
}
export -f mirror
parallel mirror {} {.}_mirror.pdf ::: "$@"

