#!/bin/bash

: <<=cut
=pod

=head1 NAME

gitnext - Checkout next git revision


=head1 SYNOPSIS

gitnext


=head1 DESCRIPTION

B<gitnext> does the opposite of B<git checkout HEAD^>. So instead of
stepping backwards in time, it steps forwards.


=head1 EXAMPLE

Go to next revision

  gitnext

=head1 AUTHOR

Copyright (C) 2017 Ole Tange,
http://ole.tange.dk and Free Software Foundation, Inc.


=head1 LICENSE

Copyright (C) 2012 Free Software Foundation, Inc.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
at your option any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.


=head1 DEPENDENCIES

B<gitnext> uses B<git>.


=head1 SEE ALSO

B<git>


=cut

git checkout $(git log --reverse --ancestry-path HEAD..master|head -n 1|field 2)
